openapi: 3.0.0
info:
  title: Camunda Customer Process API
  description: REST API Calls from message sendTask BPMN elements in Camunda process
  version: 1.0.0
servers:
  - url: http://api.example.com/Consumer/v1
    description: Example server
  - url: http://192.168.0.15:8000/sandbox/Customer/v1
    description: Sandbox kong local server
  - url: http://189.122.101.71:8000/sandbox/Customer/v1
    description: Kong external gateway
paths:
  /Customer:
    get:
      summary: Retrieve Customer catalog
      operationId: retrieveCustomerCatalog
      tags:
        - Customer
      responses:
        '200':
          description: Successful retrieval of customer catalog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerCatalog'
      security:
        - bearerAuth: []
  
components:
  schemas:
    CustomerCatalog:
      type: array
      items:
        type: object
        properties:
          FiscalNumber:
            type: integer
          id:
            type: integer
          location:
            type: string
          name:
            type: string
     
