openapi: 3.0.0
info:
  title: Insurance Process API
  description: API endpoints for managing health care insurance processes
  version: 1.0.0
servers:
  - url: http://192.168.0.15:8000/sandbox/Process_Insurance/v1
    description: Sandbox kong local server
  - url: http://189.60.52.78:8000/sandbox/Process_Insurance/v1
    description: Kong external gateway

paths:
  /Consultant/AssessApplication:
    post:
      summary: Assess insurance application
      operationId: assessApplication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenericRequest'      
      responses:
        '200':
          description: Successful operation
      security:
        - oauth2: []

  /Consultant/SaveProcessStatus:
    post:
      summary: Save process status
      operationId: saveProcessStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveProcessStatusRequest'      
      responses:
        '200':
          description: Successful operation
      security:
        - oauth2: []

  /Consultant/UpdateProcesStatus:
    post:
      summary: Update process status
      operationId: updateProcessStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProcessStatusRequest'      
      responses:
        '200':
          description: Successful operation
      security:
        - oauth2: []

  /Consultant/InformAboutAcceptance:
    post:
      summary: Inform about acceptance
      operationId: informAboutAcceptance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenericRequest'      
      responses:
        '200':
          description: Successful operation
      security:
        - oauth2: []

  /Consultant/InformAboutRejection:
    post:
      summary: Inform about rejection
      operationId: informAboutRejection
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenericRequest'      
      responses:
        '200':
          description: Successful operation
      security:
        - oauth2: []

  /Consultant/InformAboutOffer:
    post:
      summary: Inform about offer
      operationId: informAboutOffer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenericRequest'      
      responses:
        '200':
          description: Successful operation
      security:
        - oauth2: []

  /Consultant/SaveCustomerData:
    post:
      summary: Save customer data
      operationId: saveCustomerData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveCustomerDataRequest'      
      responses:
        '200':
          description: Successful operation
      security:
        - oauth2: []

  /Consultant/SendContract:
    post:
      summary: Send contract
      operationId: sendContract
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenericRequest'      
      responses:
        '200':
          description: Successful operation
      security:
        - oauth2: []

components:
  schemas:
    SaveCustomerDataRequest:
      type: object
      properties:
        businessKey:
          type: string
          example: "offer6"
        variables:
          type: object
          properties:
            CustomerEmail:
              type: object
              properties:
                type:
                  type: string
                  example: "string"
                value:
                  type: string
                  example: "customer6@teste.com"
            CustomerID:
              type: object
              properties:
                type:
                  type: string
                  example: "string"
                value:
                  type: string
                  example: "Customer6"
            CustomerName:
              type: object
              properties:
                type:
                  type: string
                  example: "string"
                value:
                  type: string
                  example: "Customer 6 Name"
            businessKey:
              type: object
              properties:
                type:
                  type: string
                  example: "string"
                value:
                  type: string
                  example: "offer6"
    SaveProcessStatusRequest:
      type: object
      properties:
        Customer:
          type: string
          example: "Customer7"
        businessKey:
          type: string
          example: "offer7"
        description:
          type: string
          example: "Application received - we will soon begin with the assessment"
        status:
          type: string
          example: "started"
    UpdateProcessStatusRequest:
      type: object
      properties:
        CustomerID:
          type: string
          example: "Customer7"
        businessKey:
          type: string
          example: "offer7"
        description:
          type: string
          example: "Initial application rejected - an alternative offer will be created for you"
        process_status:
          type: string
          example: "alternative"        
    GenericRequest:
      type: object
      properties:
        businessKey:
          type: string
          example: "${execution.processBusinessKey}"
        messageName:
          type: string
          example: "Message_to_Customer-Statusupdate_2_Application-Assesment-2"
        variables:
          type: object
          properties:
            CustomerID:
              type: object
              properties:
                value:
                  type: string
                  example: "${CustomerID}"
                type:
                  type: string
                  example: "string"
            CustomerEmail:
              type: object
              properties:
                value:
                  type: string
                  example: "${CustomerEmail}"
                type:
                  type: string
                  example: "string"
            CustomerName:
              type: object
              properties:
                value:
                  type: string
                  example: "${CustomerName}"
                type:
                  type: string
                  example: "string"
            businessKey:
              type: object
              properties:
                value:
                  type: string
                  example: "${execution.processBusinessKey}"
                type:
                  type: string
                  example: "string"
            assesment_decision:
              type: object
              properties:
                value:
                  type: string
                  example: "${assesment_decision}"
                type:
                  type: string
                  example: "string"            

  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations
