openapi: 3.0.0
info:
  title: Archi Insurance Claim
  description: API endpoints for the insurance claim
  version: 1.0.0
servers:
  - url: https://api.example.com/handle-claim/v1
    description: Production server
  - url: https://api.staging.example.com/handle-claim/v1
    description: Staging server
  - url: http://192.168.0.15:8000/sandbox/handle-claim/v1
    description: Local development server
paths:
  /claims:
    get:
      summary: Get a list of claims
      responses:
        '200':
          description: Successful response with product list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/claimDetails'
    post:
      summary: Create a Claim
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/claim'
      responses:
        '201':
          description: Successful 


  /claims/{id}/capture-informations:
    get:
      summary: Get a list of claims
      responses:
        '200':
          description: Successful 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/claimDetails'


  /claims/{id}/details:
    get:
      summary: Get the details of a claim
      responses:
        '200':
          description: Successful 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/claimDetails' 

  /claims/{id}/stackholders:
    get:
      summary: Get a list of stakeholders
      responses:
        '200':
          description: Successful 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/stakeholders'                                                    
  
  /claims/{id}/notify-stakeholders:
    post:
      summary: Notify stakeholders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stackholderNotification'
      responses:
        '200':
          description: Product added successfully
        '400':
          description: Bad request, invalid input

  /claims/{id}/validations:
    post:
      summary: inform the validations of a claim
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/validations'
      responses:
        '200':
          description: Product added successfully
        '400':
          description: Bad request, invalid input
  /claims/{id}/investigation-result:
    post:
      summary: Inform the result of the investigation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/investigationResult'
      responses:
        '200':
          description: Product added successfully
        '400':
          description: Bad request, invalid input          

components:
  schemas:
    claim:
      type: object
      properties:
        client:
          type: object
          properties:
            code:
              type: string  
            name:
              type: string
            email:
              type: string
            phone:
              type: string
        objectDamage:
          type: object
          properties:
            description:
              type: string
            coverage:
              type: string
            value:
              type: string
        paymentData:
          type: object
          properties:
            bankName:
              type: string
            accountNumber:
              type: string
            brachNumber:
              type: string
            bic:
              type: string
        origin: 
          type: object
          properties:
            code:
              type: integer
            description:
              type: string
        policyNumber:
          type: string
        claimId:
          type: integer
    claimDetails:
      type: object
      properties:
        client:
          type: object
          properties:
            code:
              type: string  
            name:
              type: string
            email:
              type: string
            phone:
              type: string
        objectDamage:
          type: object
          properties:
            description:
              type: string
            coverage:
              type: string
            value:
              type: string
        paymentData:
          type: object
          properties:
            bankName:
              type: string
            accountNumber:
              type: string
            brachNumber:
              type: string
            bic:
              type: string
        origin: 
          type: object
          properties:
            code:
              type: integer
            description:
              type: string
        policyNumber:
          type: string
        claimId:
          type: integer 
        objectAddress:
          type: object
          properties:
            cep:
              type: string
            end:
              type: string
            numero:
              type: integer
            bairro:
              type: string
            cidade:
              type: string
            uf:
              type: string
    stakeholders:
      type: object
      properties:
        claimId:
          type: string  
        policyNumber:
          type: string
        insuredClient:
          type: object
          properties:
            code:
              type: string
            name:
              type: string
            email:
              type: string
        stakeholders:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              name:
                type: string
              email:
                type: string
   
    stackholderNotification:
      type: object
      properties:
        claimId:
          type: string  
        policy:
          type: string
        code:
          type: string
        name:
          type: string
        email:
          type: string
        message:
          type: string
    validations:
      type: object
      properties:
        claimId:
          type: string  
        policyNumber:
          type: string
        objectDamage:
          type: object
          properties:
            name:
              type: string
            coverage:
              type: string
            value:
              type: string
        validated:
          type: boolean
    investigationResult:
      type: object
      properties:
        claimId:
          type: string  
        policyNumber:
          type: string
        client:
          type: object
          properties:
            code:
              type: string
        objectDamage:
          type: object
          properties:
            object:
              type: string
            coverage:
              type: string
            value:
              type: string
        result:
          type: string

