openapi: 3.0.0
info:
  title: Camunda Consumer Process API
  description: REST API Calls from message sendTask BPMN elements in Camunda process
  version: 1.0.0
servers:
  - url: http://192.168.0.15:8000/sandbox/Consumer/v1
    description: Sandbox kong local server
  - url: http://189.122.101.71:8000/sandbox/Consumer/v1
    description: Kong external gateway
paths:
  /Purchase/Consume:
    post:
      summary: Create Purchase Consumer Order
      operationId: createPurchaseConsumerOrder
      tags:
        - Purchase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseConsumerOrderCreate'
      responses:
        '200':
          description: Purchase consumer order created successfully
      security:
        - bearerAuth: []    

components:
  schemas:
    PurchaseConsumerOrderCreate:
      type: object
      properties:
        TopicName:
          type: string